stages:
  - pre_clean
  - latex
  - texstudio
  - post_clean

pre_clean:
  stage: pre_clean
  tags: ['DOCKER']
  script:
    - docker image prune -a
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: on_success
    - when: never

post_clean:
  stage: post_clean
  tags: ['DOCKER']
  script:
    - docker image prune
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - when: always


#############################
###        Base           ###
#############################

.base-build:
  before_script:
    - test -z "$DOCKER_REGISTRY_PASSWORD" && echo "Provided empty password. Make sure DOCKER_REGISTRY_PASSWORD is set."
    - docker login --username "$DOCKER_REGISTRY_USER" --password "$DOCKER_REGISTRY_PASSWORD" $DOCKER_REGISTRY_DOMAIN
  tags: ['DOCKER']

  variables:
    DOCKER_REGISTRY_DOMAIN: docker.io
    DOCKER_REGISTRY_USER: raabf
    PUSH_ENABLED: 'false'

  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: on_success
    - when: manual


.build-latex:
  extends: .base-build
  stage: latex
  script:
    - ./latex/scripts/build.sh
    - ./latex/scripts/tag_alias.sh

  variables:
    DOCKERFILE_PATH: ./latex/ge-jessie.Dockerfile
    DOCKER_REGISTRY_REPO: raabf/latex-versions


.build-texstudio:
  extends: .base-build
  stage: texstudio
  script:
    - ./texstudio/scripts/build.sh
    - ./texstudio/scripts/tag_alias.sh
  variables:
    DOCKERFILE_PATH: 0
    DOCKER_REGISTRY_REPO: raabf/texstudio-versions
    TEXSTUDIO_VERSION: "4.2.3"


#############################
###        Latex          ###
#############################

l-bullseye:
  extends: .build-latex
  variables: 
    IMAGE_TAG: bullseye

l-jammy:
  extends: .build-latex
  variables: 
    IMAGE_TAG: jammy

l-bookworm:
  extends: .build-latex
  variables: 
    IMAGE_TAG: bookworm


#############################
###      Texstudio        ###
#############################

t-bullseye:
  extends: .build-texstudio
  needs: [ 'l-bullseye' ]
  variables: 
    IMAGE_TAG: bullseye
    DOCKERFILE_PATH: ./texstudio/debian-bullseye.Dockerfile

t-jammy:
  extends: .build-texstudio
  needs: [ 'l-jammy' ]
  variables: 
    IMAGE_TAG: jammy
    DOCKERFILE_PATH: ./texstudio/debian-jammy.Dockerfile

t-bookworm:
  extends: .build-texstudio
  needs: [ 'l-bookworm' ]
  variables: 
    IMAGE_TAG: bookworm
    DOCKERFILE_PATH: ./texstudio/debian-bookworm.Dockerfile
