stages:
  - latex

.build-latex:
  stage: latex
  tags: ['DOCKER']
  before_script:
    - test -z "$DOCKER_REGISTRY_PASSWORD" && echo "Provided empty password. Make sure DOCKER_REGISTRY_PASSWORD is set."
    - docker login --username "$DOCKER_REGISTRY_USER" --password "$DOCKER_REGISTRY_PASSWORD" $DOCKER_REGISTRY_DOMAIN

  script:
    - ./latex/scripts/build.sh
    - ./latex/scripts/aliastag.sh

  variables:
    DOCKERFILE_PATH: ./latex/ge-jessie.Dockerfile
    DOCKER_REGISTRY_DOMAIN: docker.io
    DOCKER_REGISTRY_REPO: raabf/latex-versions
    DOCKER_REGISTRY_USER: raabf
    PUSH_ENABLED: 'false'

foobar:
  extends: .build-latex
  variables: 
    IMAGE_TAG: foobar
  when: manual

focal:
  extends: .build-latex
  variables: 
    IMAGE_TAG: focal
  when: manual
