stages:
  - pre_clean
  - latex
  - post_clean

pre_clean:
  stage: pre_clean
  tags: ['DOCKER']
  script:
    - docker image prune -a
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: on_success
    - when: never

post_clean:
  stage: post_clean
  tags: ['DOCKER']
  script:
    - docker image prune
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - when: always

.build-latex:
  stage: latex
  tags: ['DOCKER']
  before_script:
    - test -z "$DOCKER_REGISTRY_PASSWORD" && echo "Provided empty password. Make sure DOCKER_REGISTRY_PASSWORD is set."
    - docker login --username "$DOCKER_REGISTRY_USER" --password "$DOCKER_REGISTRY_PASSWORD" $DOCKER_REGISTRY_DOMAIN

  script:
    - ./latex/scripts/build.sh
    - ./latex/scripts/aliastag.sh

  variables:
    DOCKERFILE_PATH: ./latex/ge-jessie.Dockerfile
    DOCKER_REGISTRY_DOMAIN: docker.io
    DOCKER_REGISTRY_REPO: raabf/latex-versions
    DOCKER_REGISTRY_USER: raabf
    PUSH_ENABLED: 'false'

  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: on_success
    - when: manual

foobar:
  extends: .build-latex
  variables: 
    IMAGE_TAG: foobar

focal:
  extends: .build-latex
  variables: 
    IMAGE_TAG: focal
