#!/bin/bash

# $IMAGE_NAME var is injected into the build so the tag is correct.

echo "--build hook called--"
echo "build hook: IMAGE_NAME '$IMAGE_NAME'"
echo "build hook: DOCKERFILE_PATH '$DOCKERFILE_PATH'"
echo "build hook: CACHE_TAG '$CACHE_TAG'"
echo "build hook: DOCKER_TAG '$DOCKER_TAG'"
echo "build hook: DOCKER_REPO '$DOCKER_REPO'"
echo "build hook: SOURCE_BRANCH '$SOURCE_BRANCH'"
echo "build hook: SOURCE_COMMIT '$SOURCE_COMMIT'"

declare -A basemap
declare -A versionmap
declare -A codenamemap

versionmap[wheezy]="2012";       basemap[wheezy]="debian:wheezy";             codenamemap[wheezy]="wheezy"
versionmap[trusty]="2013";       basemap[trusty]="ubuntu:trusty";             codenamemap[trusty]="trusty"
versionmap[jessie]="2014";       basemap[jessie]="debian:jessie";             codenamemap[jessie]="jessie"
versionmap[xenial]="2015";       basemap[xenial]="ubuntu:xenial";             codenamemap[xenial]="xenial"
versionmap[stretch]="2016";      basemap[stretch]="debian:stretch";           codenamemap[stretch]="stretch"
versionmap[bionic]="2017";       basemap[bionic]="ubuntu:bionic";             codenamemap[bionic]="bionic"
versionmap[buster]="2018";       basemap[buster]="debian:buster";             codenamemap[buster]="buster"
versionmap[experimental]="2019"; basemap[experimental]="debian:experimental"; codenamemap[experimental]="experimental"

docker build --build-arg BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
             --build-arg VCS_REF=$(git rev-parse --short HEAD) \
             --build-arg BASE_IMAGE="${basemap[$DOCKER_TAG]}" \
             --build-arg TEXLIVE_VERSION="${versionmap[$DOCKER_TAG]}" \
             --build-arg CODENAME="${codenamemap[$DOCKER_TAG]}" \
             --file $DOCKERFILE_PATH --tag $IMAGE_NAME .
