#!/bin/bash

# $IMAGE_NAME var is injected into the build so the tag is correct.

echo "--build hook called--"
echo "build hook: IMAGE_NAME '$IMAGE_NAME'"
echo "build hook: DOCKERFILE_PATH '$DOCKERFILE_PATH'"
echo "build hook: CACHE_TAG '$CACHE_TAG'"
echo "build hook: DOCKER_TAG '$DOCKER_TAG'"
echo "build hook: DOCKER_REPO '$DOCKER_REPO'"
echo "build hook: SOURCE_BRANCH '$SOURCE_BRANCH'"
echo "build hook: SOURCE_COMMIT '$SOURCE_COMMIT'"

declare -A basemap
declare -A versionmap
declare -A debmap

# For ubuntu in debmap it would be “http://archive.ubuntu.com/ubuntu/ trusty multiverse”, but it is already activated
versionmap[wheezy]="2012";       basemap[wheezy]="debian:wheezy";             debmap[wheezy]="deb http://deb.debian.org/debian/ wheezy contrib non-free"
versionmap[trusty]="2013";       basemap[trusty]="ubuntu:trusty";             debmap[trusty]=""
versionmap[jessie]="2014";       basemap[jessie]="debian:jessie";             debmap[jessie]="deb http://deb.debian.org/debian/ jessie contrib non-free"
versionmap[xenial]="2015";       basemap[xenial]="ubuntu:xenial";             debmap[xenial]=""
versionmap[stretch]="2016";      basemap[stretch]="debian:stretch";           debmap[stretch]="deb http://deb.debian.org/debian/ stretch contrib non-free"
versionmap[bionic]="2017";       basemap[bionic]="ubuntu:bionic";             debmap[bionic]=""
versionmap[buster]="2018";       basemap[buster]="debian:buster";             debmap[buster]="deb http://deb.debian.org/debian/ buster contrib non-free"
versionmap[experimental]="2019"; basemap[experimental]="debian:experimental"; debmap[experimental]="deb http://deb.debian.org/debian/ experimental contrib non-free"

docker build --build-arg BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
             --build-arg VCS_REF=$(git rev-parse --short HEAD) \
             --build-arg BASE_IMAGE="${basemap[$DOCKER_TAG]}" \
             --build-arg TEXLIVE_VERSION="${versionmap[$DOCKER_TAG]}" \
             --build-arg DEBLINE="${debmap[$DOCKER_TAG]}" \
             --file $DOCKERFILE_PATH --tag $IMAGE_NAME .
