#!/bin/bash

echo "--post_push hook called--"
echo "post_push: IMAGE_NAME '$IMAGE_NAME'"
echo "post_push: DOCKER_REPO '$DOCKER_REPO'"
echo "post_push: SOURCE_COMMIT '$SOURCE_COMMIT'"
echo "post_push: DOCKER_TAG '$DOCKER_TAG'"

declare -A aliasmap

aliasmap[wheezy]="texlive2012"
aliasmap[trusty]="texlive2013"
aliasmap[jessie]="texlive2014"
aliasmap[xenial]="texlive2015"
aliasmap[stretch]="texlive2016 latest"
aliasmap[buster]="texlive2017"
aliasmap[experimental]="texlive2018"


array=( $(echo ${aliasmap[$DOCKER_TAG]}) )
echo "post_push: use alias list '${aliasmap[$DOCKER_TAG]}'"

for aliastag in ${array[@]}; do
    
    echo "post_push: tag and push '$aliastag'"
    docker tag $IMAGE_NAME $DOCKER_REPO:$aliastag
    docker push $DOCKER_REPO:$aliastag

done

