#!/bin/bash

# $IMAGE_NAME var is injected into the build so the tag is correct.

echo "--build hook called--"
echo "build hook: IMAGE_NAME '$IMAGE_NAME'"
echo "build hook: DOCKERFILE_PATH '$DOCKERFILE_PATH'"

docker build --build-arg BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
            --build-arg VCS_REF=$(git rev-parse --short HEAD) \
            --env-file="$DOCKERFILE_PATH/env_file_all" \
            -f "$DOCKERFILE_PATH" -t $IMAGE_NAME .

